global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'

route:
  group_by: ['alertname', 'job', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'slack-critical'
      repeat_interval: 1h
    - match:
        severity: warning
      receiver: 'slack-warning'
      repeat_interval: 6h

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#tea-farm-ops-alerts'
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        send_resolved: true
        icon_url: 'https://avatars3.githubusercontent.com/u/3380462'
        username: 'TeaFarmOps AlertManager'

  - name: 'slack-critical'
    slack_configs:
      - channel: '#tea-farm-ops-critical'
        title: '🚨 CRITICAL: {{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        send_resolved: true
        icon_emoji: ':rotating_light:'
        username: 'TeaFarmOps Critical Alerts'

  - name: 'slack-warning'
    slack_configs:
      - channel: '#tea-farm-ops-warnings'
        title: '⚠️ WARNING: {{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        send_resolved: true
        icon_emoji: ':warning:'
        username: 'TeaFarmOps Warning Alerts'

  - name: 'email-notifications'
    email_configs:
      - to: 'admin@your-domain.com'
        from: 'alertmanager@your-domain.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'alertmanager@your-domain.com'
        auth_password: 'your-email-password'
        headers:
          subject: 'TeaFarmOps Alert: {{ template "email.subject" . }}'
        html: '{{ template "email.html" . }}'
        send_resolved: true

templates:
  - '/etc/alertmanager/template/*.tmpl'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'job', 'instance'] 