# TeaFarmOps セキュリティ設定ファイル
# 使用方法: このファイルを /etc/tea-farm-ops/security-config.yml に配置

# セキュリティシステム全体の設定
security:
  enabled: true
  mode: "production"  # production, staging, development
  auto_update: true
  notifications:
    email_enabled: true
    slack_enabled: true
    notify_on_violation: true
    notify_on_scan: false

# ファイアウォール設定
firewall:
  enabled: true
  type: "ufw"  # ufw, iptables, firewalld
  default_policy:
    incoming: "deny"
    outgoing: "allow"
  
  # 許可するポート
  allowed_ports:
    - port: 22
      protocol: "tcp"
      description: "SSH"
      rate_limit: true
    - port: 80
      protocol: "tcp"
      description: "HTTP"
      rate_limit: false
    - port: 443
      protocol: "tcp"
      description: "HTTPS"
      rate_limit: false
    - port: 8080
      protocol: "tcp"
      description: "Spring Boot API"
      rate_limit: true
    - port: 3000
      protocol: "tcp"
      description: "React Dev Server"
      rate_limit: false
    - port: 5432
      protocol: "tcp"
      description: "PostgreSQL"
      source: "127.0.0.1"
      rate_limit: true
    - port: 9090
      protocol: "tcp"
      description: "Prometheus"
      rate_limit: true
    - port: 3001
      protocol: "tcp"
      description: "Grafana"
      rate_limit: true
    - port: 9093
      protocol: "tcp"
      description: "Alertmanager"
      rate_limit: true
  
  # 拒否するサービス
  denied_services:
    - "telnet"
    - "ftp"
    - "rsh"
    - "rlogin"
    - "finger"
    - "tftp"
  
  # レート制限設定
  rate_limiting:
    ssh_max_attempts: 3
    ssh_time_window: 300
    general_max_attempts: 10
    general_time_window: 60

# SSL/TLS設定
ssl:
  enabled: true
  provider: "letsencrypt"  # letsencrypt, self-signed, custom
  auto_renew: true
  renewal_days_before_expiry: 30
  
  # ドメイン設定
  domains:
    - "your-domain.com"
    - "www.your-domain.com"
    - "api.your-domain.com"
  
  # セキュリティヘッダー
  security_headers:
    hsts_enabled: true
    hsts_max_age: 31536000
    hsts_include_subdomains: true
    hsts_preload: false
    x_frame_options: "DENY"
    x_content_type_options: "nosniff"
    x_xss_protection: "1; mode=block"
    referrer_policy: "strict-origin-when-cross-origin"
    content_security_policy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:; frame-ancestors 'none';"
  
  # 暗号化設定
  ciphers:
    protocols: ["TLSv1.2", "TLSv1.3"]
    preferred_ciphers: "ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384"
    session_cache: "shared:SSL:10m"
    session_timeout: "10m"

# SSH設定
ssh:
  enabled: true
  port: 22
  protocol: 2
  
  # 認証設定
  authentication:
    permit_root_login: false
    pubkey_authentication: true
    password_authentication: false
    permit_empty_passwords: false
    challenge_response_authentication: false
    use_pam: true
  
  # セッション設定
  session:
    x11_forwarding: false
    print_motd: false
    print_last_log: true
    tcp_keep_alive: true
    client_alive_interval: 300
    client_alive_count_max: 2
  
  # セキュリティ設定
  security:
    max_auth_tries: 3
    max_sessions: 10
    login_grace_time: 60
    strict_modes: true
    permit_user_environment: false
    compression: "delayed"
  
  # 接続制限
  access_control:
    allowed_users: ["teafarmops"]
    denied_users: ["root"]
    allowed_groups: []
    denied_groups: []
  
  # 暗号化設定
  encryption:
    ciphers: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
    macs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"
    kex_algorithms: "curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256"
    host_key_algorithms: "ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519"

# ユーザー管理設定
user_management:
  enabled: true
  
  # パスワードポリシー
  password_policy:
    min_length: 12
    max_age_days: 90
    min_age_days: 1
    warn_age_days: 7
    require_uppercase: true
    require_lowercase: true
    require_digits: true
    require_special_chars: true
    prevent_reuse: 5
  
  # アカウントロックアウト
  account_lockout:
    enabled: true
    max_failed_attempts: 5
    lockout_duration_minutes: 30
    reset_after_hours: 24
  
  # 不要なユーザーの無効化
  disable_unnecessary_users: true
  unnecessary_users:
    - "games"
    - "lp"
    - "news"
    - "uucp"
    - "proxy"
    - "www-data"
    - "backup"
    - "list"
    - "irc"
    - "gnats"
    - "nobody"

# ファイル権限設定
file_permissions:
  enabled: true
  
  # 重要なファイルの権限
  critical_files:
    "/etc/passwd": "644:root:root"
    "/etc/shadow": "600:root:root"
    "/etc/group": "644:root:root"
    "/etc/gshadow": "600:root:root"
    "/etc/ssh/sshd_config": "600:root:root"
    "/etc/sudoers": "440:root:root"
    "/etc/hosts": "644:root:root"
    "/etc/resolv.conf": "644:root:root"
    "/etc/fstab": "644:root:root"
    "/etc/crontab": "644:root:root"
  
  # アプリケーションディレクトリの権限
  application_directories:
    "/app": "755:teafarmops:teafarmops"
    "/var/log/tea-farm-ops": "755:root:root"
    "/etc/tea-farm-ops": "755:root:root"
  
  # セットUID/GIDファイルの監視
  monitor_suid_sgid: true
  allowed_suid_files: []
  allowed_sgid_files: []

# セキュリティ監査設定
security_audit:
  enabled: true
  schedule:
    daily: "03:00"
    weekly: "04:00"
    monthly: "05:00"
  
  # 監査項目
  audit_items:
    system_audit: true
    network_audit: true
    user_audit: true
    package_audit: true
    log_audit: true
    vulnerability_scan: true
  
  # 脆弱性スキャン
  vulnerability_scan:
    enabled: true
    scan_ports: true
    scan_services: true
    scan_files: true
    scan_permissions: true
  
  # レポート設定
  reporting:
    generate_reports: true
    report_retention_days: 90
    email_reports: true
    include_recommendations: true

# ログ監視設定
log_monitoring:
  enabled: true
  
  # 監視するログファイル
  monitored_logs:
    - "/var/log/auth.log"
    - "/var/log/secure"
    - "/var/log/ufw.log"
    - "/var/log/nginx/access.log"
    - "/var/log/nginx/error.log"
    - "/var/log/tea-farm-ops/security/*.log"
  
  # アラート設定
  alerts:
    failed_login_attempts:
      enabled: true
      threshold: 5
      time_window_minutes: 10
    suspicious_activity:
      enabled: true
      patterns:
        - "Failed password"
        - "Invalid user"
        - "Connection closed"
        - "Authentication failure"
    file_access_violations:
      enabled: true
      monitor_critical_files: true
  
  # ログローテーション
  log_rotation:
    enabled: true
    max_size_mb: 100
    max_files: 10
    compress_old_logs: true

# 侵入検知設定
intrusion_detection:
  enabled: true
  
  # Fail2ban設定
  fail2ban:
    enabled: true
    jails:
      ssh:
        enabled: true
        max_retry: 3
        bantime: 3600
        findtime: 600
      nginx:
        enabled: true
        max_retry: 5
        bantime: 1800
        findtime: 300
      postgresql:
        enabled: true
        max_retry: 3
        bantime: 7200
        findtime: 600
  
  # リアルタイム監視
  real_time_monitoring:
    enabled: true
    monitor_network_connections: true
    monitor_file_changes: true
    monitor_process_creation: true
    monitor_user_activity: true

# バックアップセキュリティ
backup_security:
  enabled: true
  
  # バックアップの暗号化
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"
    key_rotation_days: 90
  
  # アクセス制御
  access_control:
    restrict_backup_access: true
    allowed_users: ["teafarmops"]
    require_authentication: true
  
  # 整合性チェック
  integrity_checking:
    enabled: true
    verify_backups: true
    checksum_verification: true

# パフォーマンス設定
performance:
  # セキュリティスキャンのパフォーマンス
  scan_performance:
    max_concurrent_scans: 5
    scan_timeout_seconds: 300
    resource_limit_percent: 50
  
  # ログ処理のパフォーマンス
  log_performance:
    max_log_size_mb: 100
    log_processing_timeout: 60
    batch_processing_size: 1000

# 通知設定
notifications:
  # メール通知
  email:
    enabled: true
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    smtp_username: "${SMTP_USERNAME}"
    smtp_password: "${SMTP_PASSWORD}"
    from_address: "security@your-domain.com"
    to_addresses:
      - "admin@your-domain.com"
      - "security@your-domain.com"
  
  # Slack通知
  slack:
    enabled: true
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channel: "#security-alerts"
    username: "TeaFarmOps Security"
    icon_emoji: ":shield:"
  
  # 通知イベント
  events:
    security_violation: true
    failed_login_attempts: true
    suspicious_activity: true
    system_compromise: true
    backup_failure: true
    certificate_expiry: true
    audit_completion: true

# テスト設定
testing:
  enabled: true
  
  # セキュリティテスト
  security_tests:
    port_scan_test: true
    vulnerability_test: true
    authentication_test: true
    authorization_test: true
  
  # テスト環境
  test_environment:
    test_domain: "test.your-domain.com"
    test_user: "testuser"
    test_data: "/tmp/security-test-data"
  
  # テストスケジュール
  test_schedule:
    daily_tests: "02:00"
    weekly_tests: "03:00"
    monthly_tests: "04:00"

# コンプライアンス設定
compliance:
  enabled: true
  
  # 規制コンプライアンス
  regulations:
    gdpr:
      enabled: true
      data_retention_days: 2555  # 7 years
      data_encryption: true
      access_logging: true
    sox:
      enabled: true
      audit_trail: true
      access_controls: true
    pci_dss:
      enabled: false
      card_data_encryption: false
      access_monitoring: false
  
  # セキュリティフレームワーク
  frameworks:
    nist_cybersecurity:
      enabled: true
      identify: true
      protect: true
      detect: true
      respond: true
      recover: true
    iso_27001:
      enabled: true
      information_security: true
      risk_management: true
      continuous_improvement: true

# 緊急時対応設定
emergency_response:
  enabled: true
  
  # 自動対応
  automated_response:
    block_suspicious_ips: true
    disable_compromised_accounts: true
    isolate_affected_systems: true
    backup_critical_data: true
  
  # エスカレーション
  escalation:
    enabled: true
    levels:
      - level: 1
        contacts: ["admin@your-domain.com"]
        response_time_minutes: 30
      - level: 2
        contacts: ["security@your-domain.com", "emergency@your-domain.com"]
        response_time_minutes: 15
      - level: 3
        contacts: ["emergency@your-domain.com", "phone:+1234567890"]
        response_time_minutes: 5
  
  # 復旧手順
  recovery_procedures:
    system_restore: true
    data_recovery: true
    service_restart: true
    communication_plan: true 